// frontend/src/components/SleeperImport.vue
<template>
  <div class="sleeper-import">
    <div class="search-section">
      <h2>Import Sleeper League</h2>
      <div class="search-box">
        <input 
          v-model="username" 
          type="text" 
          placeholder="Enter Sleeper username"
          @keyup.enter="searchLeagues"
        />
        <button @click="searchLeagues" :disabled="isLoading">
          {{ isLoading ? 'Searching...' : 'Search' }}
        </button>
      </div>
    </div>

    <div v-if="error" class="error-message">
      {{ error }}
    </div>

    <div v-if="user" class="user-info">
      <h3>User Found: {{ user.display_name }}</h3>
    </div>

    <div v-if="leagues.length > 0" class="leagues-list">
      <h3>Available Leagues</h3>
      <div class="league-cards">
        <div v-for="league in leagues" :key="league.league_id" class="league-card">
          <div class="league-info">
            <h4>{{ league.name }}</h4>
            <p>Season: {{ league.season }}</p>
            <p>Status: {{ league.status }}</p>
          </div>
          <button 
            @click="importLeague(league.league_id)"
            :disabled="isImporting"
            class="import-button"
          >
            {{ isImporting ? 'Importing...' : 'Import League' }}
          </button>
        </div>
      </div>
    </div>

    <div v-if="!leagues.length && searched" class="no-leagues">
      No leagues found for this user.
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'

const router = useRouter()
const username = ref('')
const user = ref(null)
const leagues = ref([])
const error = ref('')
const isLoading = ref(false)
const isImporting = ref(false)
const searched = ref(false)

const searchLeagues = async () => {
  if (!username.value) {
    error.value = 'Please enter a username'
    return
  }

  error.value = ''
  isLoading.value = true
  searched.value = true

  try {
    const response = await axios.get(`/sleeper/search?username=${username.value}`)
    if (response.data.success) {
      user.value = response.data.user
      leagues.value = response.data.leagues
    } else {
      error.value = response.data.error || 'Failed to fetch leagues'
    }
  } catch (err) {
    error.value = err.response?.data?.error || 'An error occurred while searching'
  } finally {
    isLoading.value = false
  }
}

const importLeague = async (leagueId) => {
  error.value = ''
  isImporting.value = true

  try {
    const response = await axios.post('/sleeper/import', { league_id: leagueId })
    if (response.data.success) {
      // Redirect to the league page after successful import
      router.push(`/league/${response.data.league_id}`)
    } else {
      error.value = response.data.error || 'Failed to import league'
    }
  } catch (err) {
    error.value = err.response?.data?.error || 'An error occurred while importing'
  } finally {
    isImporting.value = false
  }
}
</script>

<style scoped>
.sleeper-import {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.search-section {
  margin-bottom: 30px;
}

.search-box {
  display: flex;
  gap: 10px;
  margin-top: 15px;
}

input {
  flex: 1;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
}

button {
  padding: 10px 20px;
  background-color: #4CAF50;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  transition: background-color 0.3s;
}

button:disabled {
  background-color: #cccccc;
  cursor: not-allowed;
}

button:hover:not(:disabled) {
  background-color: #45a049;
}

.error-message {
  color: #ff0000;
  margin: 10px 0;
  padding: 10px;
  background-color: #ffe6e6;
  border-radius: 4px;
}

.user-info {
  margin: 20px 0;
  padding: 15px;
  background-color: #f5f5f5;
  border-radius: 4px;
}

.leagues-list {
  margin-top: 30px;
}

.league-cards {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
  margin-top: 15px;
}

.league-card {
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 15px;
  background-color: white;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.league-info {
  margin-bottom: 15px;
}

.league-info h4 {
  margin: 0 0 10px 0;
  color: #333;
}

.league-info p {
  margin: 5px 0;
  color: #666;
}

.import-button {
  width: 100%;
  margin-top: 10px;
}

.no-leagues {
  text-align: center;
  color: #666;
  margin-top: 20px;
  padding: 20px;
  background-color: #f5f5f5;
  border-radius: 4px;
}
</style>

// frontend/src/SleeperImport.jsx
import { useState, useEffect } from 'react';
import { API_BASE_URL } from './config';

function SleeperImport() {
    const [username, setUsername] = useState('');
    const [user, setUser] = useState(null);
    const [leagues, setLeagues] = useState([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const searchLeagues = async () => {
        const sessionToken = localStorage.getItem('sessionToken');
        if (!sessionToken) {
            setError('Please log in to search for Sleeper leagues.');
            return;
        }

        if (!username) {
            setError('Please enter a Sleeper username.');
            return;
        }

        setLoading(true);
        setError(null);

        try {
            const response = await fetch(`${API_BASE_URL}/sleeper/search?username=${encodeURIComponent(username)}`, {
                headers: { 'Authorization': sessionToken }
            });
            const text = await response.text(); // Get raw text first
            console.log("Raw response:", text); // Log raw response for debugging
            const data = JSON.parse(text); // Try to parse as JSON
            if (data.success) {
                setUser(data.user);
                setLeagues(data.leagues);
            } else {
                setError(data.error || 'Failed to search for leagues');
                setUser(null);
                setLeagues([]);
            }
        } catch (err) {
            setError('Error searching for leagues: ' + err.message);
            setUser(null);
            setLeagues([]);
        } finally {
            setLoading(false);
        }
    };

    const importLeague = async (leagueId) => {
        const sessionToken = localStorage.getItem('sessionToken');
        if (!sessionToken) {
            setError('Please log in to import a league.');
            return;
        }

        setLoading(true);
        setError(null);

        try {
            const response = await fetch(`${API_BASE_URL}/sleeper/import`, {
                method: 'POST',
                headers: {
                    'Authorization': sessionToken,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ league_id: leagueId })
            });
            const data = await response.json();
            if (data.success) {
                alert('League imported successfully!');
                // Optionally, redirect or update UI
            } else {
                setError(data.error || 'Failed to import league');
            }
        } catch (err) {
            setError('Error importing league: ' + err.message);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        const sessionToken = localStorage.getItem('sessionToken');
        if (!sessionToken) {
            setError('Please log in to access this page.');
        }
    }, []);

    return (
        <div className="container p-4">
            <h1 className="display-4 fw-bold mb-4">Import Sleeper League</h1>
            <div className="mb-3">
                <label htmlFor="username" className="form-label">Sleeper Username</label>
                <div className="input-group">
                    <input
                        type="text"
                        className="form-control"
                        id="username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        placeholder="Enter Sleeper username"
                    />
                    <button
                        className="btn btn-primary"
                        onClick={searchLeagues}
                        disabled={loading}
                    >
                        {loading ? 'Searching...' : 'Search'}
                    </button>
                </div>
            </div>
            {error && <div className="alert alert-danger">{error}</div>}
            {user && (
                <div className="mb-3">
                    <h3>User Found: {user.display_name}</h3>
                </div>
            )}
            {leagues.length > 0 && (
                <div>
                    <h3>Available Leagues</h3>
                    <div className="row">
                        {leagues.map(league => (
                            <div key={league.league_id} className="col-md-4 mb-3">
                                <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">{league.name}</h5>
                                        <p className="card-text">Season: {league.season}</p>
                                        <button
                                            className="btn btn-success"
                                            onClick={() => importLeague(league.league_id)}
                                            disabled={loading}
                                        >
                                            Import League
                                        </button>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}

export default SleeperImport;
